index:
    path: /main
    controller: App\Controller\MainController::index

add_post:
    path: /addpost
    controller: App\Controller\AddPostController::Add

show_post:
    path: /showpost
    controller: App\Controller\ShowPostController::show

show_one:
    path: /showone/{id}
    controller: App\Controller\ShowPostController::showOne